# Generated by Django 2.0.4 on 2018-05-08 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kusaco', '0002_auto_20180508_2059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
