# Generated by Django 2.0.4 on 2018-05-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusaco', '0003_delete_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('capacity', models.CharField(max_length=30)),
                ('year_joined', models.DateField()),
                ('year_graduated', models.DateField()),
                ('email', models.CharField(blank=True, max_length=50)),
                ('phone', models.IntegerField(blank=True)),
                ('testimonial', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
